apiVersion: v1
kind: Namespace
metadata:
  name: business-automation
  labels:
    name: business-automation
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: business-automation-quota
  namespace: business-automation
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: business-automation-limits
  namespace: business-automation
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim