apiVersion: v1
kind: ServiceAccount
metadata:
  name: business-automation-sa
  namespace: business-automation
  labels:
    app: business-automation
    component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: business-automation-role
  namespace: business-automation
  labels:
    app: business-automation
    component: rbac
rules:
# Allow reading ConfigMaps and Secrets
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Allow reading Services for service discovery
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Allow reading Pods for health checks
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Allow creating Events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: business-automation-rolebinding
  namespace: business-automation
  labels:
    app: business-automation
    component: rbac
subjects:
- kind: ServiceAccount
  name: business-automation-sa
  namespace: business-automation
roleRef:
  kind: Role
  name: business-automation-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: business-automation-monitoring-sa
  namespace: business-automation
  labels:
    app: business-automation
    component: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: business-automation-monitoring-role
  labels:
    app: business-automation
    component: monitoring
rules:
# Allow reading metrics from all namespaces
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: business-automation-monitoring-rolebinding
  labels:
    app: business-automation
    component: monitoring
subjects:
- kind: ServiceAccount
  name: business-automation-monitoring-sa
  namespace: business-automation
roleRef:
  kind: ClusterRole
  name: business-automation-monitoring-role
  apiGroup: rbac.authorization.k8s.io