apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: business-automation-vpa
  namespace: default
  labels:
    app: business-automation
    component: vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: business-automation-services
  updatePolicy:
    updateMode: "Auto" # Can be "Off", "Initial", or "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: api-gateway
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
    - containerName: task-orchestrator
      minAllowed:
        cpu: 200m
        memory: 256Mi
      maxAllowed:
        cpu: 4
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
    - containerName: ai-ml-engine
      minAllowed:
        cpu: 500m
        memory: 1Gi
      maxAllowed:
        cpu: 8
        memory: 16Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
    - containerName: data-analytics
      minAllowed:
        cpu: 300m
        memory: 512Mi
      maxAllowed:
        cpu: 6
        memory: 12Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: business-automation-metrics
  namespace: default
  labels:
    app: business-automation
    component: monitoring
spec:
  selector:
    matchLabels:
      app: business-automation
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    honorLabels: true
  - port: health
    interval: 10s
    path: /health
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: business-automation-alerts
  namespace: default
  labels:
    app: business-automation
    component: alerting
spec:
  groups:
  - name: business-automation.performance
    interval: 30s
    rules:
    # High CPU usage alert
    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{pod=~"business-automation-.*"}[5m]) * 100 > 80
      for: 2m
      labels:
        severity: warning
        component: performance
      annotations:
        summary: "High CPU usage detected"
        description: "Pod {{ $labels.pod }} has CPU usage above 80% for more than 2 minutes"
    
    # High memory usage alert
    - alert: HighMemoryUsage
      expr: (container_memory_working_set_bytes{pod=~"business-automation-.*"} / container_spec_memory_limit_bytes) * 100 > 85
      for: 2m
      labels:
        severity: warning
        component: performance
      annotations:
        summary: "High memory usage detected"
        description: "Pod {{ $labels.pod }} has memory usage above 85% for more than 2 minutes"
    
    # High response time alert
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="business-automation"}[5m])) > 1
      for: 1m
      labels:
        severity: warning
        component: performance
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is above 1 second for more than 1 minute"
    
    # High error rate alert
    - alert: HighErrorRate
      expr: rate(http_requests_total{job="business-automation",status=~"5.."}[5m]) / rate(http_requests_total{job="business-automation"}[5m]) * 100 > 5
      for: 1m
      labels:
        severity: critical
        component: performance
      annotations:
        summary: "High error rate detected"
        description: "Error rate is above 5% for more than 1 minute"
    
    # Queue length alert
    - alert: HighQueueLength
      expr: task_queue_length > 100
      for: 2m
      labels:
        severity: warning
        component: performance
      annotations:
        summary: "High task queue length"
        description: "Task queue length is above 100 for more than 2 minutes"
    
    # Pod restart alert
    - alert: PodRestartingFrequently
      expr: rate(kube_pod_container_status_restarts_total{pod=~"business-automation-.*"}[15m]) > 0
      for: 0m
      labels:
        severity: warning
        component: reliability
      annotations:
        summary: "Pod restarting frequently"
        description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last 15 minutes"
    
    # Scaling event alert
    - alert: FrequentScaling
      expr: rate(hpa_scaling_events_total{hpa="business-automation-hpa"}[10m]) > 0.1
      for: 5m
      labels:
        severity: info
        component: autoscaling
      annotations:
        summary: "Frequent scaling events"
        description: "HPA is scaling frequently, which may indicate unstable load patterns"
    
    # Resource limit alert
    - alert: NearResourceLimit
      expr: (kube_deployment_status_replicas{deployment="business-automation-services"} / kube_deployment_spec_replicas{deployment="business-automation-services"}) > 0.9
      for: 5m
      labels:
        severity: warning
        component: capacity
      annotations:
        summary: "Near maximum replica count"
        description: "Deployment is running at {{ $value | humanizePercentage }} of maximum replicas"

  - name: business-automation.availability
    interval: 30s
    rules:
    # Service availability alert
    - alert: ServiceUnavailable
      expr: up{job="business-automation"} == 0
      for: 1m
      labels:
        severity: critical
        component: availability
      annotations:
        summary: "Service is unavailable"
        description: "Service {{ $labels.instance }} has been unavailable for more than 1 minute"
    
    # Database connection alert
    - alert: DatabaseConnectionIssues
      expr: database_connections_active / database_connections_max > 0.8
      for: 2m
      labels:
        severity: warning
        component: database
      annotations:
        summary: "High database connection usage"
        description: "Database connection pool is above 80% capacity"
    
    # Cache hit rate alert
    - alert: LowCacheHitRate
      expr: cache_hit_rate < 0.7
      for: 5m
      labels:
        severity: warning
        component: cache
      annotations:
        summary: "Low cache hit rate"
        description: "Cache hit rate is below 70% for more than 5 minutes"

  - name: business-automation.business
    interval: 60s
    rules:
    # Workflow failure rate alert
    - alert: HighWorkflowFailureRate
      expr: rate(workflow_executions_total{status="failed"}[10m]) / rate(workflow_executions_total[10m]) * 100 > 10
      for: 5m
      labels:
        severity: warning
        component: business
      annotations:
        summary: "High workflow failure rate"
        description: "Workflow failure rate is above 10% for more than 5 minutes"
    
    # AI model performance alert
    - alert: AIModelPerformanceDegraded
      expr: ai_model_accuracy < 0.8
      for: 10m
      labels:
        severity: warning
        component: ai
      annotations:
        summary: "AI model performance degraded"
        description: "AI model accuracy has dropped below 80% for more than 10 minutes"
    
    # Task processing backlog alert
    - alert: TaskProcessingBacklog
      expr: task_processing_backlog_hours > 2
      for: 15m
      labels:
        severity: critical
        component: business
      annotations:
        summary: "Task processing backlog"
        description: "Task processing backlog is above 2 hours"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: performance-dashboard-config
  namespace: default
  labels:
    app: business-automation
    component: monitoring
data:
  dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Business Automation Performance",
        "tags": ["business-automation", "performance"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "CPU Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{pod=~\"business-automation-.*\"}[5m]) * 100",
                "legendFormat": "{{ pod }}"
              }
            ],
            "yAxes": [
              {
                "label": "CPU %",
                "max": 100,
                "min": 0
              }
            ]
          },
          {
            "id": 2,
            "title": "Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "container_memory_working_set_bytes{pod=~\"business-automation-.*\"} / 1024 / 1024",
                "legendFormat": "{{ pod }}"
              }
            ],
            "yAxes": [
              {
                "label": "Memory (MB)",
                "min": 0
              }
            ]
          },
          {
            "id": 3,
            "title": "Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total{job=\"business-automation\"}[5m])",
                "legendFormat": "{{ method }} {{ status }}"
              }
            ],
            "yAxes": [
              {
                "label": "Requests/sec",
                "min": 0
              }
            ]
          },
          {
            "id": 4,
            "title": "Response Time",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket{job=\"business-automation\"}[5m]))",
                "legendFormat": "p50"
              },
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=\"business-automation\"}[5m]))",
                "legendFormat": "p95"
              },
              {
                "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{job=\"business-automation\"}[5m]))",
                "legendFormat": "p99"
              }
            ],
            "yAxes": [
              {
                "label": "Response Time (s)",
                "min": 0
              }
            ]
          },
          {
            "id": 5,
            "title": "Error Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total{job=\"business-automation\",status=~\"5..\"}[5m]) / rate(http_requests_total{job=\"business-automation\"}[5m]) * 100",
                "legendFormat": "Error Rate %"
              }
            ],
            "yAxes": [
              {
                "label": "Error Rate %",
                "max": 100,
                "min": 0
              }
            ]
          },
          {
            "id": 6,
            "title": "Auto-scaling Events",
            "type": "graph",
            "targets": [
              {
                "expr": "kube_deployment_status_replicas{deployment=\"business-automation-services\"}",
                "legendFormat": "Current Replicas"
              },
              {
                "expr": "kube_deployment_spec_replicas{deployment=\"business-automation-services\"}",
                "legendFormat": "Desired Replicas"
              }
            ],
            "yAxes": [
              {
                "label": "Replica Count",
                "min": 0
              }
            ]
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }