env:
  contexts:
    - name: "Business Automation API"
      urls:
        - "http://localhost:3000/api/v1"
      includePaths:
        - "http://localhost:3000/api/v1/.*"
      excludePaths:
        - "http://localhost:3000/api/v1/health"
        - "http://localhost:3000/api/v1/metrics"
      authentication:
        method: "json"
        loginUrl: "http://localhost:3000/api/v1/auth/login"
        loginRequestData: '{"email":"security-test@test.com","password":"SecurityTest123!"}'
        usernameParameter: "email"
        passwordParameter: "password"
        loginIndicator: "token"
        logoutIndicator: "Unauthorized"
      sessionManagement:
        method: "cookie"
        sessionTokens:
          - "token"
      users:
        - name: "test-user"
          credentials:
            email: "security-test@test.com"
            password: "SecurityTest123!"
        - name: "admin-user"
          credentials:
            email: "admin-security@test.com"
            password: "AdminSecurity123!"

  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  - type: "passiveScan-config"
    parameters:
      maxAlertsPerRule: 10
      scanOnlyInScope: true

  - type: "spider"
    parameters:
      context: "Business Automation API"
      user: "test-user"
      maxDuration: 10
      maxDepth: 5
      acceptCookies: true
      parseComments: true
      parseRobotsTxt: true
      handleODataParametersVisited: true

  - type: "spiderAjax"
    parameters:
      context: "Business Automation API"
      user: "test-user"
      maxDuration: 10
      maxCrawlDepth: 5
      numberOfBrowsers: 1
      inScopeOnly: true

  - type: "activeScan"
    parameters:
      context: "Business Automation API"
      user: "test-user"
      maxRuleDurationInMins: 5
      maxScanDurationInMins: 30
      addQueryParam: false
      defaultPolicy: "Default Policy"
      delayInMs: 0
      handleAntiCSRFTokens: true
      injectPluginIdInHeader: true
      scanHeadersAllRequests: true
      threadPerHost: 2

  - type: "report"
    parameters:
      template: "traditional-html"
      reportDir: "testing/security/reports"
      reportFile: "security-report"
      reportTitle: "Business Automation Security Scan"
      reportDescription: "Automated security testing report"

  - type: "report"
    parameters:
      template: "traditional-json"
      reportDir: "testing/security/reports"
      reportFile: "security-report"